name: PVPDeathWin
version: 1.5
main: com.gmail.gogobebe2.pvpdeathwin.PVPDeathWin
description: A death match plugin.
 
commands:
    pvp:
        usage: /<command>
        description: Main plugin command.
    teams:
        usage: /<command>
        description: Displays each teams players.
    dlimit:
        usage: /<command>
        description: Set death limit to lose.
    reset:
            usage: /<command>
            description: Reset Red & Blue players and scores.
       
permissions:
    pvp.use:
        description: Is allowed to use this plugin's admin commands.
        default: op

    
